# docker-compose.yml
services:
  postgres:
    image: postgres:16-alpine
    container_name: sarvasync-postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password123
      POSTGRES_DB: sarvasync_express_db
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - bun-network

  pgadmin:
    image: dpage/pgadmin4:8
    container_name: sarvasync-pgadmin
    restart: unless-stopped
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin123
    ports:
      - "8080:80"
    depends_on:
      - postgres
    networks:
      - bun-network
    volumes:
      - pgadmin_data:/var/lib/pgadmin
      
volumes:
  postgres_data:
  pgadmin_data:

networks:
  bun-network:
    driver: bridge