# docker-compose.dev.yml

services:
  api:
    build:
      context: .
      target: dev 
    container_name: sarvasync-api-dev
    ports:
      - "3000:3000"
    env_file:
      - .env
    volumes:
      - .:/usr/src/app 
      - /usr/src/app/node_modules 
    depends_on:
      - postgres
    networks:
      - bun-network
    command: bun run --hot src/index.ts

  analytics-worker: 
    build:
      context: .
      target: dev 
    container_name: sarvasync-analytics-worker-dev
    env_file:
      - .env 
    volumes:
      - .:/usr/src/app 
      - /usr/src/app/node_modules
    depends_on:
      - postgres 
    networks:
      - bun-network 
    command: bun run --hot src/workers/analytics-sync.ts